language: bash

dist: bionic

services:
  - docker

before_install:
  - sudo rm -f /etc/apt/sources.list.d/pgdg.list
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get -y install bats

install:
  - export UBUNTU_DOCKER_IMAGE=ubuntu:latest
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch
  - git checkout master
  - cd dockerfiles/apache
  - travis_retry make build-without-cache
  - cd "$TRAVIS_BUILD_DIR"
  - cd dockerfiles/haproxy
  - ./edit-dockerfile.sh insert_content02 Dockerfile > Dockerfile.tmp
  - mv -f Dockerfile.tmp Dockerfile
  #- sed -i '/^global.*/a insecure-fork-wanted' files/haproxy_front.cfg
  - travis_retry make build-without-cache
  - cd "$TRAVIS_BUILD_DIR"

script:
  - make test

after_script:
  - make clean

notifications:
  email:
    - haproxy.cert.otf.travis@gmail.com
